In [1]:
import random
import import_ipynb
from data_utils import *

importing Jupyter notebook from data_utils.ipynb


In [2]:
def get_id2line():
    lines=open('./data/movie_lines.txt').read().split('\n')
    id2line = {}
    for line in lines:
        _line = line.split(' +++$+++ ')
        if len(_line) == 5:
            id2line[_line[0]] = _line[4]
    return id2line

In [3]:
def get_conversations():
    conv_lines = open('./data/movie_conversations.txt').read().split('\n')
    convs = [ ]
    for line in conv_lines[:-1]:
        _line = line.split(' +++$+++ ')[-1][1:-1].replace("'","").replace(" ","")
        convs.append(_line.split(','))
    return convs

In [4]:
def extract_conversations(convs,id2line,path=''):
    idx = 0
    for conv in convs:
        f_conv = open(path + str(idx)+'.txt', 'w')
        for line_id in conv:
            f_conv.write(id2line[line_id])
            f_conv.write('\n')
        f_conv.close()
        idx += 1

In [5]:
def gather_dataset(convs, id2line):
    questions = []; answers = []

    for conv in convs:
        if len(conv) %2 != 0:
            conv = conv[:-1]
        for i in range(len(conv)):
            if i%2 == 0:
                questions.append(id2line[conv[i]])
            else:
                answers.append(id2line[conv[i]])

    return questions, answers

In [7]:
def prepare_seq2seq_files(questions, answers, path='',TESTSET_SIZE = 30000):
    
    # open files
    train_enc = open(path + 'train.enc','w')
    train_dec = open(path + 'train.dec','w')
    test_enc  = open(path + 'test.enc', 'w')
    test_dec  = open(path + 'test.dec', 'w')

    # choose 30,000 (TESTSET_SIZE) items to put into testset
    test_ids = random.sample([i for i in range(len(questions))],TESTSET_SIZE)

    for i in range(len(questions)):
        if i in test_ids:
            test_enc.write(questions[i]+'\n')
            test_dec.write(answers[i]+ '\n' )
        else:
            train_enc.write(questions[i]+'\n')
            train_dec.write(answers[i]+ '\n' )
        if i%10000 == 0:
            print ('\n>> written %d lines' %(i) )

    # close files
    train_enc.close()
    train_dec.close()
    test_enc.close()
    test_dec.close()

In [15]:
import numpy as np

In [16]:
sample_idx = random.sample(list(np.arange(10000)), 128)
sample_idx

[8397,
 4791,
 1630,
 1560,
 5228,
 1487,
 1476,
 557,
 1874,
 1449,
 7452,
 4737,
 4593,
 6058,
 3792,
 2808,
 21,
 7890,
 8032,
 4896,
 3914,
 7861,
 9018,
 7380,
 5881,
 2898,
 4413,
 2329,
 7198,
 302,
 3720,
 4007,
 8274,
 8859,
 7479,
 5956,
 3337,
 3096,
 9685,
 1977,
 6817,
 3407,
 5598,
 8774,
 5312,
 8875,
 4130,
 2727,
 2643,
 9137,
 3527,
 3269,
 2754,
 1798,
 3621,
 1749,
 7665,
 5314,
 6436,
 2809,
 8447,
 7871,
 2540,
 9738,
 1305,
 942,
 704,
 2563,
 9565,
 9707,
 2322,
 365,
 5641,
 9858,
 3973,
 9093,
 9111,
 8608,
 3549,
 7794,
 2736,
 1574,
 3625,
 9855,
 5810,
 7545,
 4128,
 8881,
 3962,
 6615,
 6381,
 984,
 4821,
 8851,
 9050,
 3187,
 4090,
 8653,
 9562,
 2691,
 3141,
 2635,
 4717,
 2683,
 3816,
 6545,
 283,
 6105,
 8696,
 851,
 6202,
 8136,
 6933,
 8983,
 353,
 8846,
 9942,
 8027,
 494,
 5841,
 7832,
 8893,
 8186,
 2778,
 9035,
 4394,
 3429,
 7800]

In [8]:
id2line = get_id2line()
print ('>> gathered id2line dictionary.\n')

>> gathered id2line dictionary.



In [9]:
convs = get_conversations()
print ('>> gathered conversations.\n')

>> gathered conversations.



In [10]:
questions, answers = gather_dataset(convs,id2line)

In [11]:
print (questions[:2])

['Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.', 'Not the hacking and gagging and spitting part.  Please.']


In [13]:
print (answers[:2])

["Well, I thought we'd start with pronunciation, if that's okay with you.", "Okay... then how 'bout we try out some French cuisine.  Saturday?  Night?"]


In [14]:
len(questions), len(answers)

(138135, 138135)

In [1]:
import tensorflow as tf

In [25]:
a=tf.random.uniform(shape=[2, 3, 5])

In [26]:
b=a.numpy

In [27]:
b

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[0.9750303 , 0.00209427, 0.81627285, 0.24198401, 0.5030347 ],
        [0.29694057, 0.2931838 , 0.18645084, 0.0504961 , 0.85390663],
        [0.67352045, 0.3358636 , 0.57445467, 0.04066014, 0.7076626 ]],

       [[0.06680918, 0.5612142 , 0.00214863, 0.30019283, 0.15338421],
        [0.20401728, 0.8455086 , 0.28445888, 0.275851  , 0.54548335],
        [0.79705226, 0.36229265, 0.53688955, 0.5081047 , 0.781672  ]]],
      dtype=float32)>>

In [28]:
import numpy as np

In [29]:
b= np.array(a)

In [30]:
b.shape

(2, 3, 5)

In [31]:
b.transpose([1,0,2]).shape

(3, 2, 5)

In [33]:
b.transpose([1,0,2])

array([[[0.9750303 , 0.00209427, 0.81627285, 0.24198401, 0.5030347 ],
        [0.06680918, 0.5612142 , 0.00214863, 0.30019283, 0.15338421]],

       [[0.29694057, 0.2931838 , 0.18645084, 0.0504961 , 0.85390663],
        [0.20401728, 0.8455086 , 0.28445888, 0.275851  , 0.54548335]],

       [[0.67352045, 0.3358636 , 0.57445467, 0.04066014, 0.7076626 ],
        [0.79705226, 0.36229265, 0.53688955, 0.5081047 , 0.781672  ]]],
      dtype=float32)

# Many to Many problem understanding

In [34]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [35]:
X = list()
Y = list()
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

In [37]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

In [38]:
model = Sequential()

In [39]:
model.add(LSTM(100, activation='relu', input_shape=(3, 1)))

In [40]:
model.add(RepeatVector(3))

In [41]:
model.add(LSTM(100, activation='relu', return_sequences=True))

In [42]:
model.add(TimeDistributed(Dense(1)))

In [43]:
model.compile(optimizer='adam', loss='mse')

In [44]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 100)               40800     
                                                                 
 repeat_vector (RepeatVector  (None, 3, 100)           0         
 )                                                               
                                                                 
 lstm_1 (LSTM)               (None, 3, 100)            80400     
                                                                 
 time_distributed (TimeDistr  (None, 3, 1)             101       
 ibuted)                                                         
                                                                 
Total params: 121,301
Trainable params: 121,301
Non-trainable params: 0
_________________________________________________________________


In [45]:
X = list()
Y = list()
X1 = [x1 for x1 in range(5, 301, 5)]
X2 = [x2 for x2 in range(20, 316, 5)]
Y = [y for y in range(35, 331, 5)]

X = np.column_stack((X1, X2))

In [49]:
X.shape, len(X1), len(X2)

((60, 2), 60, 60)

In [50]:
X = np.array(X).reshape(20, 3, 2)
Y = np.array(Y).reshape(20, 3, 1)

In [51]:
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(3, 2)))
model.add(RepeatVector(3))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

In [52]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

Epoch 1/1000
6/6 [==============================] - 2s 75ms/step - loss: 22227.3086 - val_loss: 45162.5273
Epoch 2/1000
6/6 [==============================] - 0s 10ms/step - loss: 10297.2539 - val_loss: 18641.6211
Epoch 3/1000
6/6 [==============================] - 0s 11ms/step - loss: 5532.8652 - val_loss: 17047.4922
Epoch 4/1000
6/6 [==============================] - 0s 12ms/step - loss: 4388.8057 - val_loss: 12376.2979
Epoch 5/1000
6/6 [==============================] - 0s 11ms/step - loss: 3406.5269 - val_loss: 9506.5586
Epoch 6/1000
6/6 [==============================] - 0s 11ms/step - loss: 2626.9436 - val_loss: 7250.3359
Epoch 7/1000
6/6 [==============================] - 0s 10ms/step - loss: 1923.7974 - val_loss: 5128.9448
Epoch 8/1000
6/6 [==============================] - 0s 10ms/step - loss: 1168.3988 - val_loss: 2186.7202
Epoch 9/1000
6/6 [==============================] - 0s 10ms/step - loss: 359.6182 - val_loss: 1035.3286
Epoch 10/1000
6/6 [==============================]

In [53]:
X1 = [300, 305, 310]
X2 = [315, 320, 325]

test_input = np.column_stack((X1, X2))

test_input = test_input.reshape((1, 3, 2))
print(test_input)

[[[300 315]
  [305 320]
  [310 325]]]


In [54]:
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[[331.1507 ]
  [337.14847]
  [343.16235]]]


In [ ]:
def remove_start_tag(input_with_start_tag: str):
        return ' '.join(input_with_start_tag.split()[1:])

In [2]:
' '.join('START_ hi there _END'.split()[1:])

'hi there _END'

In [58]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

model = Sequential()
model.add(Bidirectional(LSTM(100, activation='relu', input_shape=(3, 2))))
model.add(RepeatVector(3))
model.add(Bidirectional(LSTM(100, activation='relu', return_sequences=True)))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)



Epoch 1/1000


TypeError: in user code:

    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\venka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\backend.py", line 2134, in dot
        out = tf.matmul(x, y)

    TypeError: Exception encountered when calling layer "lstm_cell_17" (type LSTMCell).
    
    Input 'b' of 'MatMul' Op has type float32 that does not match type int32 of argument 'a'.
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 2), dtype=int32)
      • states=('tf.Tensor(shape=(None, 100), dtype=int32)', 'tf.Tensor(shape=(None, 100), dtype=int32)')
      • training=True


In [ ]:
test_output = model.predict(test_input, verbose=0)
print(test_output)